### ISSUE TITLE
[FSW] - code for Aspen lab up/left/right/down test

### ISSUE THREAD

**Issue by LyonFoster** [ARDVARC/ARDVARC#105]
### Summary Here
**Assigned to: @LyonFoster ** 

**Supported by: @Tim-Behrer @aidanwoodcu **

**Urgency: Urgent **

_Date to complete by: 3/8/24

<details><summary> 

this is the guidance code for the first test in the aspen lab where we're going to switch to off board control and expect the drone to go a meter up, a meter to the left, a meter back to the right, and remain there hovering.

apparently we probably won't be able to do "off board" in the aspen lab but I guess we'll have this ready anyways.

</summary>
<p>

**TODO**

- [ ] send [0,0,0] until read "off board" from client
- [ ] after off board is read, send [1,0,1] wait 10 seconds [0,0,1]
- [ ] relinquish control if needed and let pilot switch to "manual" and land it on the ground
- [ ] verify [0,0,0] is the spot where the drone arms from and not where the drone switches to off board mode or something else weird

</p>
</details>
