### ISSUE TITLE
[FSW] - The Full Monty

### ISSUE THREAD

**Issue by LyonFoster** [ARDVARC/ARDVARC#110]
### Summary Here
**Assigned to: @LyonFoster ** 

**Urgency: 5**

_Date to complete by: 3/23/24

<details><summary> 
Attempt at the full guidance. Going to try to build up to it, orbit and POI the origin then depending on the mission state replace the origin with the relevant rgv.

</summary>
<p>

**TODO (in this order)**

- [ ] Orbit and POI the origin
- [ ] Orbit and POI RGV1 using the spoofed values
- [ ] Orbit and POI both rgvs depending on mission state
- [ ] Figure out how to handle joint
- [ ] figure out what to do neat the mission boundaries
- [ ] close the loop with estimation if that ever happens

**Consider**
-  How about you consider my balls

</p>
</details>
