### ISSUE TITLE
[FSW] - Finalize CV

### ISSUE THREAD

**Issue by Tim-Behrer** [ARDVARC/ARDVARC#115]
### Summary Here
**Assigned to: @Tim-Behrer ** 

**Supported by: @LyonFoster **

**Urgency: 4*

<details><summary> Issue Details</summary>
<p>

**TODO**

- [ ] Calibrate proper resolution videos for intrinsics and distortion
- [ ] Fisheye^^
- [ ] Telephoto^^^
- [ ] Test with calibrated camera
- [ ] Clean up commented out portions and old code
- [ ] Clear done TODOs

**Consider**
- Calibration and testing

</p>
</details>

**Comment by Tim-Behrer** [comment]
Re-Open in ROSARDVARC
