### ISSUE TITLE
[FSW] - Create the MVP for estimate_rgv_state.py

### ISSUE THREAD

**Issue by Tim-Behrer** [ARDVARC/ARDVARC#87]
### Build the Estimate RGV state.py function. Create a functioning script for the MVP.
**Assigned to: @katebenic** 

**Supported by: @Tim-Behrer**

**Urgency: 3**

_Date to complete by: 02/19/24_

<details><summary> Issue Details</summary>
<p>

**TODO**

- [ ] Determine Input Format
- [ ] Work on the ROS topics/msg buses 
- [ ] Apply some filtering method to turn pointing vectors into a RGV state
- [ ] Workout frame transitions 
- [ ] How we should estimate true frames

**Consider**
- Consider the option to upgrade from fmincon
- Ensure that the frame transitions are correct

</p>
</details>

**Comment by Tim-Behrer** [comment]
Re-open in ROSARDVARC for enhancements, merge version 1.0 into main
