### ISSUE TITLE
[FSW] - start listening to the pipe with process_bluetooth.py

### ISSUE THREAD

**Issue by Tim-Behrer** [ARDVARC/ARDVARC#89]
### Talk to Rob about what is coming through the pipe and start thinking on frame transitions
**Assigned to: @katebenic** 

**Supported by: @rosc3222**

**Urgency: 2**

_Date to complete by: 02/19/24_

<details><summary> Issue Details</summary>
<p>

**TODO**

- [ ] Talk to rob on how he wants to hand us the data
- [ ] Figure out ROS topic msg format
- [ ] Start thinking about the necessary processing methods

**Consider**
-  Please think about the format CV will give pointing vectors and how to standardize

</p>
</details>

**Comment by Tim-Behrer** [comment]
@joda2486 Can you get to a good stopping point and merge, then re-open issue in ROSARDVARC
