### ISSUE TITLE
[FSW] - Implement process_frame.py 

### ISSUE THREAD

**Issue by Tim-Behrer** [ARDVARC/ARDVARC#90]
### Debug, enhance, and Implement the existing ArUco tag detector.
**Assigned to: @Tim-Behrer** 

**Supported by: @LyonFoster**

**Urgency: 4**

_Date to complete by: 02/14/24_

<details><summary> Issue Details</summary>
<p>

**TODO**

- [x] Implement AruCo detection software
- [ ] Create a sub-function to convert object detection to a pointing vector in the inertial frame.
- [x] Start thinking about camera calibration
- [x] Pose estimation

**Consider**
- Think about the camera frame and how to determine an accurate extrinsic matrix

</p>
</details>
