### ISSUE TITLE
[FSW] - SUMMARY

### ISSUE THREAD

**Issue by LyonFoster** [ARDVARC/ARDVARC#92]
### Setpoint/waypoint generation
**Assigned to: @LyonFoster ** 

**Supported by: @aidanwoodcu, @katebenic  **

**Urgency: 3**

_Date to complete by: 2/19/24_

<details><summary> Issue Details</summary>
<p>

**TODO**

- [ ] spoof some rgv state data 
- [ ] set orbit params in config/constants
- [ ] generator orbits for single rgv tracking (add joint later)
- [ ] "unit test" by graphing/plotting the set points for a given rgv path

**Consider**
- spoofing some rgv data
- mission state dependent decision making

</p>
</details>
