### ISSUE TITLE
[FSW] - Guidance

### ISSUE THREAD

**Issue by LyonFoster** [ARDVARC/ARDVARC#95]
### Summary Here
**Assigned to: @LyonFoster * 

**Urgency:4?**

_Date to complete by: before we fly the bih

<details><summary> This is the container for all guidance todos /summary>
<p>

**TODO**

- [ ] Make it so that guidance doesn't arm the uas and switch it into off board mode--make it wait until the PIC does those
- [ ] make it do an orbit
- [ ] make it do some yaw/pointing that makes sense
- [ ] delete `inout` module
- [ ] delete `offb_node`

**Consider**
-  man if I forget to make it not arm the uas and switch it to off board we are so fucked, so @Tim-Behrer and everyone else please make sure I do that

</p>
</details>

**Comment by Tim-Behrer** [comment]
Lets Re-open or adjust this issue in the ROSARDVARC repo, closing for now.
