### ISSUE TITLE
[FSW] - CV Improvements

### ISSUE THREAD

**Issue by Tim-Behrer** [ARDVARC/ARDVARC#98]
### Summary Here
**Assigned to: @Tim-Behrer ** 

**Supported by: @LyonFoster **

**Urgency: 2**

_Date to complete by: 03/04/24_

<details><summary> Issue Details</summary>
<p>

**TODO**

- [x] Debug CV.py
- [x] Test CV on Test footage
- [ ] Clean up code
- [x] Update the .const file to have the proper (Expected) intrinsics
- [x] Test the pointing vectors with the test footage

**Consider**
-  Need to test the Intrinsics matrix with aruco calibration
- 

</p>
</details>
